### ISSUE TITLE
PagefindUI is not defined

### ISSUE THREAD

**Issue by paulstroot** [FriendlyUser/astro-tech-blog#70]
I came across your project when trying to figure out how to integrate PageFind into an Astro Project. I've cloned your repo from the main branch and spun it up and your site is getting the same error I am seeing in my own project. This is it:

`Uncaught ReferenceError: PagefindUI is not defined at BottomSection.astro:16:11`

Have you come across this? Seems like there is an issue declaring "new PagefindUI()". 

I'm wondering A) if it's specific to my environment, or if it was introduced in a recent update with Astro, and B) how do I fix it?

**Comment by FriendlyUser** [comment]
Usually its available in production mode for me.

Might be better to "hide" the pagefind ui in non production mode.

Can you try running `astro build` and running the static files (pagefind is meant for statically generated sites)

**Comment by paulstroot** [comment]
Thanks. I did get it to work when I ran a `yarn build` and `yarn preview`

It would be really nice to be able to run this in dev mode if anybody else discovers a way. in the meantime I am doing a check like this in my project:

```
{import.meta.env.PROD ?
        <link href="/_pagefind/pagefind-ui.css" rel="stylesheet" />
        <script src="/_pagefind/pagefind-ui.js" type="text/javascript"></script>
        <div id="search" class="ml-3"></div>
        <script>
          window.addEventListener('DOMContentLoaded', () => {
            // @ts-ignore
            new PagefindUI({ element: '#search' });
          });
        </script>
:
        <p>Search only available in production.</p>
}
```
